name: stock_investment_app
description: A Flutter application for stock investment.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0'

dependencies:
  bloc: ^9.2.0
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  http: ^1.1.0
  injectable: ^2.7.1+4
  json_annotation: ^4.10.0
  theme_tailor_annotation: ^3.1.2

dev_dependencies:
  bloc_lint: ^0.3.6
  build_runner: ^2.11.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  injectable_generator: ^2.11.1
  json_serializable: ^6.12.0
  theme_tailor: ^3.1.2
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
